In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('DATA/시도_성별_경제활동인구_총괄.csv', encoding='utf-8')
df

,행정구역(시도),성별,2013.1/2,2013.1/2.1,2013.1/2.2,2013.1/2.3,2013.1/2.4,2013.1/2.5,2013.1/2.6,2013.1/2.7,...,2022.2/2.6,2022.2/2.7,2023.1/2,2023.1/2.1,2023.1/2.2,2023.1/2.3,2023.1/2.4,2023.1/2.5,2023.1/2.6,2023.1/2.7
0,행정구역(시도),성별,15세이상인구 (천명),경제활동인구 (천명),취업자 (천명),실업자 (천명),비경제활동인구 (천명),경제활동참가율 (％),고용률 (%),실업률 (％),...,고용률 (%),실업률 (％),15세이상인구 (천명),경제활동인구 (천명),취업자 (천명),실업자 (천명),비경제활동인구 (천명),경제활동참가율 (％),고용률 (%),실업률 (％)
1,계,계,42198,26149,25322,827,16049,62.0,60.0,3.2,...,62.7,2.4,45372,29237,28432,805,16135,64.4,62.7,2.8
2,계,남자,20670,15252,14748,504,5418,73.8,71.3,3.3,...,72.1,2.4,22342,16402,15943,460,5940,73.4,71.4,2.8
3,계,여자,21528,10897,10575,323,10631,50.6,49.1,3.0,...,53.7,2.4,23030,12835,12490,345,10195,55.7,54.2,2.7
4,서울특별시,계,8587,5343,5117,226,3244,62.2,59.6,4.2,...,60.5,3.1,8466,5294,5147,147,3172,62.5,60.8,2.8
5,서울특별시,남자,4131,3000,2878,122,1131,72.6,69.7,4.1,...,68.9,3.1,4017,2837,2771,66,1180,70.6,69.0,2.3
6,서울특별시,여자,4456,2343,2239,104,2113,52.6,50.3,4.4,...,52.8,3.0,4449,2457,2376,81,1992,55.2,53.4,3.3
7,부산광역시,계,2974,1753,1683,70,1221,58.9,56.6,4.0,...,57.7,2.8,2932,1755,1695,60,1177,59.9,57.8,3.4
8,부산광역시,남자,1432,1011,966,45,421,70.6,67.5,4.4,...,67.3,2.7,1406,980,946,35,426,69.7,67.2,3.5
9,부산광역시,여자,1542,742,717,26,799,48.1,46.5,3.5,...,48.8,3.0,1526,775,750,25,751,50.8,49.1,3.3
10,대구광역시,계,2077,1243,1204,39,834,59.8,58.0,3.1,...,59.5,2.3,2075,1281,1236,45,794,61.7,59.6,3.5
11,대구광역시,남자,1005,707,680,27,298,70.3,67.6,3.8,...,69.0,2.3,1004,710,685,25,294,70.7,68.3,3.5
12,대구광역시,여자,1072,536,525,12,536,50.0,48.9,2.2,...,50.7,2.3,1071,571,551,20,500,53.3,51.4,3.5
13,인천광역시,계,2354,1515,1453,62,839,64.4,61.7,4.1,...,63.6,2.5,2613,1704,1647,57,909,65.2,63.0,3.3
14,인천광역시,남자,1163,881,840,41,283,75.7,72.2,4.6,...,72.6,2.8,1293,965,931,34,328,74.7,72.0,3.6
15,인천광역시,여자,1191,634,613,21,557,53.3,51.5,3.4,...,54.8,2.0,1320,739,716,23,582,55.9,54.2,3.1
16,광주광역시,계,1232,727,703,25,505,59.0,57.0,3.4,...,59.6,2.4,1280,793,770,22,487,61.9,60.2,2.8
17,광주광역시,남자,597,417,402,16,180,69.9,67.2,3.8,...,67.9,2.4,624,431,418,13,193,69.0,67.0,3.0
18,광주광역시,여자,635,310,301,9,325,48.8,47.4,2.8,...,51.6,2.3,655,362,352,10,294,55.2,53.7,2.6
19,대전광역시,계,1274,755,730,25,519,59.3,57.3,3.3,...,62.6,1.4,1292,816,795,21,476,63.2,61.5,2.6
20,대전광역시,남자,624,442,425,17,182,70.9,68.2,3.8,...,72.6,1.0,637,461,447,14,176,72.3,70.2,2.9
21,대전광역시,여자,650,313,305,8,337,48.2,46.9,2.6,...,53.0,2.0,654,355,347,7,299,54.2,53.1,2.1
22,울산광역시,계,934,569,560,9,365,60.9,60.0,1.5,...,60.0,2.9,957,592,572,20,365,61.9,59.7,3.4
23,울산광역시,남자,476,371,366,4,106,77.8,76.9,1.2,...,71.3,3.2,491,358,346,12,133,72.9,70.5,3.4
24,울산광역시,여자,458,199,194,4,259,43.4,42.4,2.2,...,48.2,2.4,466,234,226,8,232,50.2,48.5,3.4
25,세종특별자치시,계,-,-,-,-,-,-,-,-,...,64.2,1.5,321,214,210,5,107,66.7,65.3,2.1
26,세종특별자치시,남자,-,-,-,-,-,-,-,-,...,75.9,1.4,159,124,121,2,36,77.7,76.2,1.9
27,세종특별자치시,여자,-,-,-,-,-,-,-,-,...,52.5,1.7,162,91,88,2,71,55.9,54.5,2.5
28,경기도,계,9945,6176,5975,201,3769,62.1,60.1,3.3,...,64.2,2.4,11941,7821,7610,211,4121,65.5,63.7,2.7
29,경기도,남자,4927,3731,3603,127,1196,75.7,73.1,3.4,...,75.0,2.2,5953,4508,4378,130,1445,75.7,73.5,2.9
30,경기도,여자,5018,2445,2371,74,2572,48.7,47.3,3.0,...,53.5,2.6,5988,3313,3232,81,2675,55.3,54.0,2.5
31,강원도,계,1252,737,723,14,515,58.9,57.7,2.0,...,63.9,2.4,1327,883,861,22,444,66.5,64.9,2.5
32,강원도,남자,610,423,416,7,187,69.4,68.2,1.7,...,69.7,2.3,649,467,455,12,182,71.9,70.1,2.6
33,강원도,여자,642,314,306,7,328,48.9,47.8,2.3,...,58.2,2.5,677,416,406,10,261,61.4,59.9,2.4
34,충청북도,계,1304,805,793,13,499,61.8,60.8,1.6,...,65.9,1.5,1433,969,949,20,464,67.6,66.2,2.1
35,충청북도,남자,645,465,459,7,179,72.2,71.1,1.4,...,75.2,2.2,725,567,554,14,157,78.3,76.4,2.4
36,충청북도,여자,659,340,334,6,319,51.6,50.7,1.8,...,56.4,0.6,709,402,395,7,307,56.7,55.8,1.7
37,충청남도,계,1812,1194,1164,30,618,65.9,64.2,2.5,...,67.1,1.6,1922,1290,1255,36,631,67.1,65.3,2.8
38,충청남도,남자,909,712,694,18,197,78.4,76.4,2.5,...,76.0,1.8,981,748,728,20,232,76.3,74.2,2.7
39,충청남도,여자,904,482,470,12,422,53.3,52.0,2.5,...,57.8,1.4,941,542,527,15,399,57.6,55.9,2.9
40,전라북도,계,1525,919,899,20,606,60.2,58.9,2.2,...,63.3,1.5,1554,1012,980,32,542,65.1,63.1,3.2
41,전라북도,남자,740,532,519,13,208,71.9,70.2,2.4,...,70.4,1.5,767,546,528,19,220,71.3,68.8,3.4
42,전라북도,여자,785,386,379,7,399,49.2,48.3,1.8,...,56.4,1.5,788,466,453,13,321,59.2,57.5,2.9
43,전라남도,계,1501,970,951,19,531,64.6,63.3,2.0,...,67.3,1.4,1524,1056,1035,21,468,69.3,67.9,2.0
44,전라남도,남자,730,548,536,12,182,75.0,73.4,2.2,...,75.0,1.4,763,577,567,10,186,75.7,74.3,1.7
45,전라남도,여자,771,422,415,7,349,54.8,53.8,1.7,...,59.6,1.3,761,479,468,11,282,62.9,61.5,2.3
46,경상북도,계,2256,1457,1421,36,799,64.6,63.0,2.5,...,64.2,2.3,2316,1533,1492,41,783,66.2,64.4,2.6
47,경상북도,남자,1107,838,814,24,269,75.7,73.5,2.9,...,73.3,2.4,1161,874,849,25,287,75.3,73.1,2.9
48,경상북도,여자,1149,619,607,12,530,53.9,52.9,1.9,...,55.0,2.1,1155,659,644,15,496,57.1,55.8,2.3
49,경상남도,계,2711,1674,1642,32,1037,61.8,60.6,1.9,...,61.4,2.6,2842,1817,1781,36,1025,63.9,62.7,2.0
50,경상남도,남자,1347,1004,984,20,343,74.5,73.0,2.0,...,70.7,2.6,1426,1027,1003,23,400,72.0,70.3,2.3
51,경상남도,여자,1364,670,658,12,694,49.1,48.3,1.8,...,52.0,2.7,1416,790,777,13,626,55.8,54.9,1.6
52,제주특별자치도,계,462,312,306,6,150,67.6,66.2,2.0,...,72.2,1.7,579,407,398,9,172,70.4,68.8,2.3
53,제주특별자치도,남자,226,170,166,4,56,75.3,73.4,2.5,...,77.6,2.3,287,222,216,6,65,77.4,75.4,2.6
54,제주특별자치도,여자,236,142,140,2,94,60.2,59.3,1.4,...,66.9,1.0,292,185,182,4,107,63.5,62.3,1.9